### ISSUE TITLE
Build with -fno-exceptions .

### ISSUE THREAD

**Issue by egorovd** [Tessil/ordered-map#10]
Hello.
Whether it is possible to make that the library build with gcc flag: -fno-exceptions ?
Thank you.

**Comment by egorovd** [comment]
Yes, this no problem, but in my project the "compile error" only at these "throw" if I use "-fno-exceptions".
if you do not want to change anything, then let it remain so.

**Comment by Tessil** [comment]
Oh effectively. As I never really used -fno-exceptions, I naively thought it replaced throw statements with abort automatically.

I'm currently not at home (and will not be for the next weeks), but I will see what I can do when I come back.

**Comment by egorovd** [comment]
Thank you very much in advance! )

**Comment by egorovd** [comment]
Hi,

Yes, under Linux everything works.
Thank you. )

**Comment by Tessil** [comment]
I merged the changes to the master branch.
