### ISSUE TITLE
64 bit bucket_entry

### ISSUE THREAD

**Issue by Peach1** [Tessil/ordered-map#16]
- The map can only hold up to 2<sup>32</sup> - 1 values, that is 4 294 967 295 values.

Is there any reason for restricting it to 32 bit indexes?
Could 2<sup>64</sup> - 1 values be supported with just a trivial change? 

in ordered_hash.h, the indexes are defined as 32 bit:

```cpp
class bucket_entry
{
public:
	using index_type = std::uint_least32_t;
	using truncated_hash_type = std::uint_least32_t;
```

defining them as 64 bit would be:

```cpp
	using index_type = std::uint64_t;
	using truncated_hash_type = std::uint64_t;
```

Besides additional memory usage, are there any implications of allowing 64 bit indexes?

**Comment by Tessil** [comment]
Hello,

Sorry for the delay, I added a way to configure this through an extra `IndexType` class template parameter.

```c++
tsl::ordered_map<int, int, std::hash<int>, std::equal_to<int>, 
                 std::allocator<std::pair<int, int>>, std::vector<std::pair<int, int>>, 
                 std::uint64_t> map;
```

I'll need to test that later before merging it to the master as I don't have enough RAM on my current computer to hold a large enough map.

**Comment by Tessil** [comment]
I merge the changes to the master. See #18 for details.
