### ISSUE TITLE
serialization

### ISSUE THREAD

**Issue by karasikov** [Tessil/ordered-map#24]
Dear developers of Tessil,

Would it be possible to add serialization functions or a way to get/set internal members for faster loading of map/set?

**Comment by Tessil** [comment]
Hello,

Yes I'll see to add this possibility when I have a bit of time.

It'll be similar to [Tessil/sparse-map](https://github.com/Tessil/sparse-map#serialization) serialization.

**Comment by Tessil** [comment]
I added support for more efficient serialization, check https://github.com/Tessil/ordered-map#serialization for details.
