### ISSUE TITLE
Corrupted map from using `insert_at_position`

### ISSUE THREAD

**Issue by BenjiHansell** [Tessil/ordered-map#38]
Firstly, thank you @Tessil for your selection brilliant open source hash tables.

An example of my issue would be:

```c++
tsl::ordered_set<std::string_view> foo;
foo.emplace("kind");
foo.emplace("oldUri");
foo.emplace("newUri");
foo.insert_at_position(foo.begin(), "annotationId");
std::cout << foo.count("kind") << std::endl; // incorrectly prints "0"
```

Making further calls on the same set reveals that the "kind" key is actually present:

```c++
std::cout << foo.size() << std::endl; // correctly prints "4"
for (auto key : foo) {
  std::cout << key << ", "; // correctly prints "annotationId, kind, oldUri, newUri, "
}
std::cout << std::endl;
```

And we can even get a duplicate key to appear in the map:

```c++
foo.emplace("kind");
std::cout << foo.count("kind") << std::endl; // prints "1"
std::cout << foo.size() << std::endl; // prints "5"
for (auto key : foo) {
  std::cout << key << ", "; // prints "annotationId, kind, oldUri, newUri, kind, "
}
std::cout << std::endl;
```

That is with `Apple clang version 14.0.0 (clang-1400.0.29.202)` using libc++.

ordered-map version: 1.0.0

**Comment by Tessil** [comment]
Thank you for the report.

From a quick test with `clang++-14.0.6`  and `g+-12.2.0` with `-O3` using `libstdc++` on you provided example I get the expected results:
```
1
4
annotationId, kind, oldUri, newUri, 
1
4
annotationId, kind, oldUri, newUri,
```

I'll check more in depth when I have some time as your results are quite worrying.

**Comment by Tessil** [comment]
Thank you very much for the example.

I was able to reproduce the error and pushed a fix. Both `insert_at_position`  and `erase` are affected (not `unordered_erase` and `pop_back`). Could you try it out?

**Comment by Tessil** [comment]
I merged the PR and created a new release. Thanks for the help.

I will close the issue. Let me know if you encounter any problem and I can reopen it.

**Comment by BenjiHansell** [comment]
Many thanks for the speedy fix. It works on my end too.
